spring:
  application:
    name: finanzas-personales

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL}
    properties:
      hibernate:
        dialect: ${DB_DIALECT}